### ISSUE TITLE
Keep the order of the tools in benchmakrs

### ISSUE THREAD

**Issue by vedran-kasalica** [Workflomics/pubmetric#44]
Currently, the generated benchmarks list the tools out of order (for example `mzRecal` is always the last tool in the sequence disregarding the position in the workflow). The tools should be listed in the order they appear in the CWL file.

**Comment by Ambivalentalfa** [comment]
solved in PR 45

https://github.com/Workflomics/pubmetric/pull/45#issue-2598964443
